baseURL           = "https://sparpater.nl/"
languageCode      = "nl-nl"
title             = "Spar Pater"
theme             = "spar"

[params]

  [params.open]
    monday          = "8:00"
    tuesday         = "8:00"
    wednesday       = "8:00"
    thursday        = "8:00"
    friday          = "8:00"
    saturday        = "8:00"
    sunday          = "11:00"

  [params.closed]
    monday          = "19:00"
    tuesday         = "19:00"
    wednesday       = "19:00"
    thursday        = "19:00"
    friday          = "19:00"
    saturday        = "18:00"
    sunday          = "15:00"

  [params.logo]
    mobile          = "images/logo-mobile.svg"
    mobile_height   = "36px"
    mobile_width    = "36px"
    desktop         = "images/logo.svg"
    desktop_height  = "29px"
    desktop_width   = "217px"
    alt             = "Spar Pater Logo"

  [params.homepage_meta_tags]
    meta_description = ""


[[menu.landing]]
  name              = "Webwinkel"
  url               = "https://exloo.spar.nl/"
  weight            = 1
[[menu.landing]]
  name              = "Route"
  url               = "https://www.google.com/maps/dir//SPAR,+Hoofdstraat,+Exloo/@52.882986,6.7965679,12z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47b7ddb12f6e70d1:0x49e6bb643bff3568!2m2!1d6.8666074!2d52.8830066!3e0"
  weight            = 2
[[menu.landing]]
  name              = "Contact"
  url               = "/contact/"
  weight            = 3
[[menu.landing]]
  name              = "Over ons"
  url               = "/about/"
  weight            = 4


[permalinks]
  post              = "/:year/:month/:day/:slug/"
  pages             = "/:filename/"
